Repository djwesty/poker-chips-helper, pull requests merged in 2025-02, with the labels that each got.

#13 Mobile Application Scaffold (Issue #12)
  .eslintrc.json
  .gitignore
  .prettierrc
  .vscode/settings.json
  README.md
  app.json
  app/_layout.tsx
  app/index.tsx
  assets/fonts/SpaceMono-Regular.ttf
  assets/images/adaptive-icon.png
  assets/images/favicon.png
  assets/images/icon.png
  assets/images/partial-react-logo.png
  assets/images/react-logo.png
  assets/images/react-logo@2x.png
  assets/images/react-logo@3x.png
  assets/images/splash-icon.png
  package-lock.json
  package.json
  tsconfig.json
Labels: Small

#14 Implement Player Count Selector Component (Issue #2)
  app/index.tsx
  components/PlayerSelector.tsx
  components/__tests__/PlayerSelector.test.tsx
  package-lock.json
  package.json
Labels: Small

#15 Implement BuyInAmount Selector Component (Issue #3)
  app/index.tsx
  components/BuyInSelector.tsx
  components/__tests__/BuyInSelector.test.tsx
Labels: Medium

#16 Ability to pick the number of chip colors, and their counts (Issue #11)
  app/index.tsx
  components/ChipsSelector.tsx
  components/__tests__/ChipsSelector.test.tsx
Labels: Medium

#25 Implemented Automatic Detection of chip counts and colors # 7
  .env.example
  .gitignore
  README.md
  app.json
  app/index.tsx
  babel.config.js
  components/ChipDetection.tsx
  components/ChipDistributionSummary.tsx
  components/__tests__/ChipDetection.test.tsx
  package-lock.json
  package.json
  tsconfig.json
Labels: Medium

#28 Add app title and app icon #23
  app.json
  assets/images/icon1.png
Labels: Small

#29 Application main page, remove top bar
  .gitignore
  app/_layout.tsx
  app/index.tsx
Labels: Small

#32 Fixed welcome screen issue # 30
  .env.example
  README.md
  babel.config.js
  components/ChipDetection.tsx
  package-lock.json
  package.json
Labels: bug

#33 Displaying Chip value contribution #6
  app/index.tsx
  components/BuyInSelector.tsx
  components/ChipDistributionSummary.tsx
  components/__tests__/BuyInSelector.test.tsx
  components/__tests__/ChipDistributionSummary.test.tsx
Labels: Large

#37 Ability to save and load calculator states into two slots
  app/index.tsx
  components/CalculatorState.tsx
  components/__tests__/CalculatorState.test.tsx
  package-lock.json
  package.json
Labels: Small

#38 Restores the previous state when reopened
  app/index.tsx
  components/PersistentState.tsx
  components/__tests__/PersistentState.test.tsx
Labels: Small

#36 Update Unit Tests for BuyInSelector Component
  components/__tests__/BuyInSelector.test.tsx
Labels: Small

#42 Added instructions to build APK
  .gitignore
  README.md
Labels: documentation

#44 Fixing icon #43
  README.md
  app.json
  assets/images/icon.png
  assets/images/icon1.png
  components/__tests__/ChipDetection.test.tsx
  package-lock.json
  package.json
Labels: bug
