Repository djwesty/poker-chips-helper, pull requests merged in 2025-03, with the labels that each got.

#46 Implemented Currency Selector # 34
  app/index.tsx
  components/BuyInSelector.tsx
  components/CalculatorState.tsx
  components/ChipDistributionSummary.tsx
  components/CurrencySelector.tsx
  components/PersistentState.tsx
  components/__tests__/BuyInSelector.test.tsx
  components/__tests__/CalculatorState.test.tsx
  components/__tests__/ChipDistributionSummary.test.tsx
  components/__tests__/CurrencySelector.test.tsx
  components/__tests__/PersistentState.test.tsx
  package-lock.json
  package.json
Labels: Large

#48 Consistent Application Styling #39
  app/_layout.tsx
  app/index.tsx
  components/BuyInSelector.tsx
  components/ChipDetection.tsx
  components/ChipDistributionSummary.tsx
  components/ChipsSelector.tsx
  components/CurrencySelector.tsx
  components/PlayerSelector.tsx
  components/__tests__/BuyInSelector.test.tsx
  components/__tests__/ChipDistributionSummary.test.tsx
  components/__tests__/ChipsSelector.test.tsx
  components/__tests__/CurrencySelector.test.tsx
  components/__tests__/PlayerSelector.test.tsx
  containers/Button.tsx
  containers/Section.tsx
  containers/__tests__/Section.test.tsx
  styles/styles.ts
  util/context.ts
Labels: Medium

#49 Implemented Language Selector # 35
  app.json
  app/_layout.tsx
  app/index.tsx
  components/BuyInSelector.tsx
  components/ChipDetection.tsx
  components/ChipDistributionSummary.tsx
  components/ChipsSelector.tsx
  components/CurrencySelector.tsx
  components/__tests__/BuyInSelector.test.tsx
  components/__tests__/ChipDetection.test.tsx
  components/__tests__/ChipDistributionSummary.test.tsx
  components/__tests__/ChipsSelector.test.tsx
  i18n/en.json
  i18n/es.json
  i18n/i18n.ts
  package-lock.json
  package.json
Labels: Medium

#50 Fixed typescript errors # 47
  app/index.tsx
  components/__tests__/BuyInSelector.test.tsx
  components/__tests__/ChipDetection.test.tsx
Labels: bug

#52 Improve layout of decrement+increment buttons (Issue #51)
  app/index.tsx
  components/ChipsSelector.tsx
  components/PlayerSelector.tsx
  containers/Section.tsx
Labels: Small

#54 Fixed text input box for white chips # 53
  components/ChipsSelector.tsx
Labels: bug

#55 Improve Chip Distribution (Issue #40)
  app.json
  components/BuyInSelector.tsx
  components/ChipDistributionSummary.tsx
  components/ChipsSelector.tsx
  components/__tests__/BuyInSelector.test.tsx
  components/__tests__/ChipDistributionSummary.test.tsx
  i18n/en.json
  i18n/es.json
  styles/styles.ts
Labels: Medium

#56 Bug Fix: Image Detection setting chip colors (Issue #45)
  app/index.tsx
Labels: bug

#58 Fixed issue with extra colors of image input # 57
  components/ChipDetection.tsx
  components/__tests__/ChipDetection.test.tsx
Labels: bug

#59 Changed Styles and Screen Size for Mobile Device
  app/_layout.tsx
  app/index.tsx
  components/BuyInSelector.tsx
  components/ChipDetection.tsx
  components/ChipsSelector.tsx
  components/CurrencySelector.tsx
  components/PlayerSelector.tsx
  components/__tests__/ChipsSelector.test.tsx
  containers/Button.tsx
  containers/Picker.tsx
  containers/Section.tsx
  i18n/en.json
  i18n/es.json
  package-lock.json
  package.json
  styles/styles.ts
  util/CalculatorState.ts
  util/PersistentState.ts
  util/tests/CalculatorState.test.ts
  util/tests/PersistentState.test.ts
Labels: Medium

#61 Address skipped tests
  components/__tests__/ChipDistributionSummary.test.tsx
  components/__tests__/ChipsSelector.test.tsx
Labels: Small
